// Condensed kit types generated by scripts/condense-generation-assets.mjs

// File: core.d.ts
import type { ChildProcess } from 'node:child_process'
import type { ProcessType, UI, Mode } from '../core/enum.js'
type ModifierKeys = 'cmd' | 'ctrl' | 'shift' | 'option' | 'alt'
export interface Choice<Value = any> {
name: string
slicedName?: string
value?: Value
description?: string
slicedDescription?: string
focused?: string
img?: string
icon?: string
html?: string
hasPreview?: boolean
preview?: string | ((input: string, state: AppState) => string | Promise<string>)
previewPath?: string
  ...
}
export interface ScoredChoice {
item: Choice<{ id: string; name: string; value: any }>
score: number
matches: {
[key: string]: [number, number][]
}
_: string
}
export type PromptBounds = {
x?: number
y?: number
width?: number
height?: number
}
export type PromptDb = {
screens: {
[screenId: string]: {
[script: string]: PromptBounds
}
}
}
export type Shortcut = {
id?: string
key: string
name?: string
value?: any
onPress?: (input: string, state: AppState) => unknown | Promise<unknown>
bar?: 'right' | 'left' | ''
flag?: string
visible?: boolean
condition?: (choice: any) => boolean
}
export interface PromptData {
id: string
key: string
scriptPath: string
description: string
flags: FlagsObject
hasPreview: boolean
keepPreview?: boolean
hint: string
input: string
inputRegex: string
kitArgs: string[]
kitScript: string
  ...
}
export type Choices<Value> = (
| (string | Choice)[]
| Choice<Value>[]
| (() => Choice<Value>[])
| (() => Promise<Choice<Value>[]>)
| Promise<Choice<any>[]>
| GenerateChoices
) & {
preload?: boolean
}
export type Preview =
| string
| void
| (() => string)
| (() => void)
| (() => Promise<string>)
| (() => Promise<void>)
| ((input: string) => string)
| ((input: string) => void)
| ((input: string) => Promise<any>)
| ((input: string) => Promise<void>)
export type Panel =
| string
| void
| (() => string)
| (() => void)
| (() => Promise<string>)
| (() => Promise<void>)
| ((input: string) => string)
| ((input: string) => void)
| ((input: string) => Promise<any>)
| ((input: string) => Promise<void>)
export type Flags = {
[key: string]: boolean | string
} & Partial<Record<ModifierKeys, boolean | string>>
export type FlagsObject = FlagsWithKeys | boolean
export type ActionsConfig = {
name?: string
placeholder?: string
active?: string
}
export type Action = {
name: string
description?: string
value?: any
shortcut?: string
group?: string
flag?: string
visible?: boolean
enter?: string
onAction?: ChannelHandler
condition?: Shortcut['condition']
close?: boolean
index?: number
}
input?: string,
state?: AppState
) => void | symbol | Promise<void | symbol>
export type PromptConfig = {
validate?: (input: string) => boolean | string | Promise<boolean | string>
choices?: Choices<any> | Panel
actions?: Action[] | Panel
initialChoices?: Choices<any> | Panel
html?: string
formData?: any
className?: string
flags?: FlagsObject
actions?: Action[]
preview?:
| string
| ((input: string, state: AppState) => string | Promise<string> | void | Promise<void>)
  ...
} & Partial<Omit<PromptData, 'choices' | 'id' | 'script' | 'preview'>>
type OptModifier = 'opt' | 'option' | 'alt'
type CmdModifier = 'cmd' | 'command'
type CtrlModifier = 'ctrl' | 'control'
type ShiftModifier = 'shift'
type Modifier = OptModifier | CmdModifier | CtrlModifier | ShiftModifier
type Key = string
type Separator = ' ' | '+'
type ModifierCombination =
| Modifier
| `${Modifier}${Separator}${Modifier}`
| `${Modifier}${Separator}${Modifier}${Separator}${Modifier}`
| `${Modifier}${Separator}${Modifier}${Separator}${Modifier}${Separator}${Modifier}`

// File: globals.d.ts
type ReadFileOptions = Parameters<typeof import('node:fs/promises').readFile>[1]
path: string,
defaultContent?: string,
options?: ReadFileOptions
) => Promise<string>
path: string,
defaultContent: T,
options?: Parameters<typeof import('fs-extra').readJson>[1]
) => Promise<T>
declare global {
var cwd: typeof process.cwd
var pid: typeof process.pid
var stderr: typeof process.stderr
var stdin: typeof process.stdin
var stdout: typeof process.stdout
var uptime: typeof process.uptime
var get: import('axios').AxiosInstance['get']
var put: import('axios').AxiosInstance['put']
var post: import('axios').AxiosInstance['post']
var patch: import('axios').AxiosInstance['patch']
var del: import('axios').AxiosInstance['delete']
var chalk: typeof import('chalk').default
var spawn: typeof import('child_process').spawn
var spawnSync: typeof import('child_process').spawnSync
var fork: typeof import('child_process').fork
var ensureReadFile: EnsureReadFile
var ensureReadJson: EnsureReadJson
var exec: typeof import('execa').execaCommand
var execa: typeof import('execa').execa
var execaSync: typeof import('execa').execaSync
var execaCommand: typeof import('execa').execaCommand
var execaCommandSync: typeof import('execa').execaCommandSync
var execaNode: typeof import('execa').execaNode
var $: typeof import('execa').$
var download: typeof import('download')
var emptyDir: typeof import('fs-extra').emptyDir
var emptyDirSync: typeof import('fs-extra').emptyDirSync
var ensureFile: typeof import('fs-extra').ensureFile
var ensureFileSync: typeof import('fs-extra').ensureFileSync
var ensureDir: typeof import('fs-extra').ensureDir
var ensureDirSync: typeof import('fs-extra').ensureDirSync
var ensureLink: typeof import('fs-extra').ensureLink
var ensureLinkSync: typeof import('fs-extra').ensureLinkSync
var ensureSymlink: typeof import('fs-extra').ensureSymlink
var ensureSymlinkSync: typeof import('fs-extra').ensureSymlinkSync
var mkdirp: typeof import('fs-extra').mkdirp
var mkdirpSync: typeof import('fs-extra').mkdirpSync
var mkdirs: typeof import('fs-extra').mkdirs
var outputFile: typeof import('fs-extra').outputFile
var outputFileSync: typeof import('fs-extra').outputFileSync
var outputJson: typeof import('fs-extra').outputJson
var outputJsonSync: typeof import('fs-extra').outputJsonSync
var pathExists: typeof import('fs-extra').pathExists
var pathExistsSync: typeof import('fs-extra').pathExistsSync
var readJson: typeof import('fs-extra').readJson
var readJsonSync: typeof import('fs-extra').readJsonSync
var remove: typeof import('fs-extra').remove
var removeSync: typeof import('fs-extra').removeSync
var writeJson: typeof import('fs-extra').writeJson
var writeJsonSync: typeof import('fs-extra').writeJsonSync
var move: typeof import('fs-extra').move
var moveSync: typeof import('fs-extra').moveSync
var readFile: typeof import('node:fs/promises').readFile
var readFileSync: typeof import('node:fs').readFileSync
var writeFile: typeof import('node:fs/promises').writeFile
var writeFileSync: typeof import('node:fs').writeFileSync
var appendFile: typeof import('node:fs/promises').appendFile
var appendFileSync: typeof import('node:fs').appendFileSync
var readdir: typeof import('node:fs/promises').readdir
var readdirSync: typeof import('node:fs').readdirSync
var copyFile: typeof import('node:fs/promises').copyFile
var copyFileSync: typeof import('node:fs').copyFileSync
var stat: typeof import('node:fs/promises').stat
var lstat: typeof import('node:fs/promises').lstat
var rmdir: typeof import('node:fs/promises').rmdir
var unlink: typeof import('node:fs/promises').unlink
var symlink: typeof import('node:fs/promises').symlink
var readlink: typeof import('node:fs/promises').readlink
var realpath: typeof import('node:fs/promises').realpath
var access: typeof import('node:fs/promises').access
var chown: typeof import('fs/promises').chown
var lchown: typeof import('node:fs/promises').lchown
var utimes: typeof import('node:fs/promises').utimes
var lutimes: typeof import('node:fs/promises').lutimes
var rename: typeof import('node:fs/promises').rename
var createReadStream: typeof import('fs').createReadStream
var createWriteStream: typeof import('fs').createWriteStream
var compile: typeof import('handlebars').compile
var md: typeof import('../globals/marked').md
var marked: typeof import('marked').marked
var uuid: typeof import('node:crypto').randomUUID
var replace: typeof import('replace-in-file').replaceInFile
var Writable: typeof import('node:stream').Writable
var Readable: typeof import('node:stream').Readable
var Duplex: typeof import('node:stream').Duplex
var Transform: typeof import('node:stream').Transform
var globby: typeof import('globby').globby
}

// File: io.d.ts
import { EventEmitter } from 'node:events'
export declare enum EventType {
EVENT_KEY_PRESSED = 4,
EVENT_KEY_RELEASED = 5,
EVENT_MOUSE_CLICKED = 6,
EVENT_MOUSE_PRESSED = 7,
EVENT_MOUSE_RELEASED = 8,
EVENT_MOUSE_MOVED = 9,
EVENT_MOUSE_WHEEL = 11,
}
export declare enum WheelDirection {
VERTICAL = 3,
HORIZONTAL = 4,
}
export declare const UiohookKey: {
readonly Backspace: 14
readonly Tab: 15
readonly Enter: 28
readonly CapsLock: 58
readonly Escape: 1
readonly Space: 57
readonly PageUp: 3657
readonly PageDown: 3665
readonly End: 3663
readonly Home: 3655
readonly ArrowLeft: 57419
readonly ArrowUp: 57416
readonly ArrowRight: 57421
readonly ArrowDown: 57424
readonly Insert: 3666
readonly Delete: 3667
readonly 0: 11
readonly 1: 2
readonly 2: 3
readonly 3: 4
readonly 4: 5
readonly 5: 6
readonly 6: 7
readonly 7: 8
readonly 8: 9
readonly 9: 10
readonly A: 30
readonly B: 48
readonly C: 46
readonly D: 32
readonly E: 18
readonly F: 33
readonly G: 34
readonly H: 35
readonly I: 23
readonly J: 36
readonly K: 37
readonly L: 38
readonly M: 50
readonly N: 49
readonly O: 24
readonly P: 25
readonly Q: 16
readonly R: 19
readonly S: 31
readonly T: 20
readonly U: 22
readonly V: 47
readonly W: 17
readonly X: 45
readonly Y: 21
readonly Z: 44
readonly Numpad0: 82
readonly Numpad1: 79
readonly Numpad2: 80
readonly Numpad3: 81
readonly Numpad4: 75
readonly Numpad5: 76
readonly Numpad6: 77
readonly Numpad7: 71
readonly Numpad8: 72
readonly Numpad9: 73
readonly NumpadMultiply: 55
readonly NumpadAdd: 78
readonly NumpadSubtract: 74
readonly NumpadDecimal: 83
readonly NumpadDivide: 3637
readonly NumpadEnd: number
readonly NumpadArrowDown: number
readonly NumpadPageDown: number
readonly NumpadArrowLeft: number
readonly NumpadArrowRight: number
readonly NumpadHome: number
readonly NumpadArrowUp: number
readonly NumpadPageUp: number
readonly NumpadInsert: number
readonly NumpadDelete: number
readonly F1: 59
readonly F2: 60
readonly F3: 61
readonly F4: 62
readonly F5: 63
readonly F6: 64
readonly F7: 65
readonly F8: 66
readonly F9: 67
readonly F10: 68
readonly F11: 87
readonly F12: 88
readonly F13: 91
readonly F14: 92
readonly F15: 93
readonly F16: 99
readonly F17: 100
readonly F18: 101
readonly F19: 102
readonly F20: 103
readonly F21: 104
readonly F22: 105
readonly F23: 106
readonly F24: 107
readonly Semicolon: 39
readonly Equal: 13
readonly Comma: 51
readonly Minus: 12
readonly Period: 52
readonly Slash: 53
readonly Backquote: 41
readonly BracketLeft: 26
readonly Backslash: 43
readonly BracketRight: 27
readonly Quote: 40
readonly Ctrl: 29
readonly CtrlRight: 3613
readonly Alt: 56
readonly AltRight: 3640
readonly Shift: 42
readonly ShiftRight: 54
readonly Meta: 3675
readonly MetaRight: 3676
readonly NumLock: 69
readonly ScrollLock: 70
readonly PrintScreen: 3639
}
declare interface UiohookNapi {
on(
event: 'input',
listener: (e: UiohookKeyboardEvent | UiohookMouseEvent | UiohookWheelEvent) => void
): this
on(event: 'keydown', listener: (e: UiohookKeyboardEvent) => void): this
on(event: 'keyup', listener: (e: UiohookKeyboardEvent) => void): this
on(event: 'mousedown', listener: (e: UiohookMouseEvent) => void): this
on(event: 'mouseup', listener: (e: UiohookMouseEvent) => void): this
on(event: 'mousemove', listener: (e: UiohookMouseEvent) => void): this
on(event: 'click', listener: (e: UiohookMouseEvent) => void): this
on(event: 'wheel', listener: (e: UiohookWheelEvent) => void): this
}
declare class UiohookNapi extends EventEmitter {
private handler
start(): void
stop(): void
keyTap(key: number, modifiers?: number[]): void
keyToggle(key: number, toggle: 'down' | 'up'): void
}
export declare const uIOhook: UiohookNapi

// File: kit.d.ts
import type { Low } from 'lowdb'
import type { format, formatDistanceToNow } from '../utils/date.js'
import type { RestEndpointMethodTypes } from '@octokit/plugin-rest-endpoint-methods'
import type {
Action,
Choice,
Choices,
FlagsObject,
ActionsConfig,
Panel,
Preview,
PromptConfig,
ScoredChoice,
Script,
Shortcut,
Flags,
} from './core.js'
import { ChannelHandler } from './core.js'
import type { ConfigOptions, Options } from 'quick-score'
import type { CoreMessage, Tool, ToolCall, FinishReason, LanguageModel, LanguageModelV1 } from 'ai'
import type { AssistantOutcome, AssistantLastInteraction, ToolCallPart } from '../lib/ai.js' // Import our custom result types
import type { ZodTypeAny } from 'zod' // Import Zod types for global declaration
export interface Arg {
[key: string]: any
<T = string>(
placeholderOrConfig?: string | PromptConfig,
choicesOrPanel?: Choices<T> | Panel,
actionsOrPreview?: Action[] | Preview
): Promise<T>
}
export type Select = <T = any[]>(
placeholderOrConfig: string | PromptConfig,
choices: Choices<T>,
actions?: Action[]
) => Promise<T>
export type Grid = <T = any[]>(
placeholderOrConfig: string | PromptConfig,
choices: Choices<T>,
actions?: Action[]
) => Promise<T>
export interface EnvConfig extends PromptConfig {
reset?: boolean
}
export interface Env {
(envKey: string, promptConfig?: string | EnvConfig | (() => Promise<string>)): Promise<string>
[key: string]: any
}
export interface Args extends Array<string> {}
export type UpdateArgs = (args: string[]) => void
export type PathFn = (...pathParts: string[]) => string
export type Inspect = (data: any, extension?: string) => Promise<void>
export type Store = (
key: string,
initialData?: any
) => Promise<InstanceType<typeof import('keyv').default>>
type DBExtensions<T> = {
data: T extends string[] ? { items: T } : T
dbPath: string
clear: () => Promise<void>
reset: () => Promise<void>
}
type DBItems<T> = T extends string[] ? { items: T } : {}
export type DB = <
T = {
[key: string]: any
},
>(
dataOrKeyOrPath?: DBKeyOrPath<T>,
data?: DBData<T>,
fromCache?: boolean
) => Promise<DBReturnType<T>>
file: string,
dir?: string,
line?: string | number,
col?: string | number
) => Promise<void>
export type Browse = (url: string) => Promise<void>
export type Wait = (time: number, submitValue?: any) => Promise<void>
export type GetScripts = (fromCache?: boolean) => Promise<Script[]>
export interface SelectScript {
(message?: string, fromCache?: boolean, xf?: (x: Script[]) => Script[]): Promise<Script>
(
message: PromptConfig,
fromCache?: boolean,
xf?: (x: Script[]) => Script[]
): Promise<Script | string>
}
markdown: string,
containerClass?: string,
injectStyles?: string
) => Promise<string>
type PathPicker = (config?: string | PathConfig, actions?: Action[]) => Promise<string>
type GistOptions = {
fileName?: string
description?: string
isPublic?: boolean
}
export type CreateGist = (
content: string,
options?: GistOptions
) => Promise<RestEndpointMethodTypes['gists']['create']['response']['data']>
interface KeyValue {
[key: string]: any
}
export type Run = (command?: string, ...args: string[]) => Promise<any>
type Utils = typeof import('../core/utils')
declare global {
var path: PathSelector
var edit: Edit
var browse: Browse
var kitPath: PathFn
var kenvPath: PathFn
var tmpPath: PathFn
var kenvTmpPath: PathFn
var attemptImport: KitModuleLoader
var silentAttemptImport: KitModuleLoader
var npm: KitModuleLoader
var npmInstall: (packageName: string) => Promise<void>
var installMissingPackage: (packageName: string) => Promise<void>
var run: Run
var setup: KitModuleLoader
var env: Env
var arg: Arg
var select: Select
var grid: Grid
var basePrompt: Arg
var mini: Arg
var micro: Arg
var onTab: OnTab
var args: Args
var updateArgs: UpdateArgs
var argOpts: string[]
var wait: Wait
var home: PathFn
var isFile: IsCheck
var isDir: IsCheck
var isBin: IsCheck
var createPathResolver: PathResolver
var inspect: Inspect
var db: DB
var store: Store
var memoryMap: Map<string, any>
var onTabIndex: number
var selectKitEditor: SelectKitEditor
var getScripts: GetScripts
var blur: () => Promise<void>
var flag: Flags
var actionFlag: string
var setFlags: FlagFn
var setActions: ActionsFn
var openActions: () => Promise<void>
var closeActions: () => Promise<void>
var setFlagValue: (value: any) => Promise<void>
var prepFlags: PrepFlags
var selectScript: SelectScript
var selectKenv: SelectKenv
var highlight: Highlight
var terminal: (script: string) => Promise<string>
var iterm: (iterm: string) => Promise<string>
var hyper: (hyper: string) => Promise<string>
var projectPath: PathFn
var clearAllTimeouts: () => void
var clearAllIntervals: () => void
var createGist: CreateGist
var setShortcuts: SetShortcuts
var isWin: boolean
var isMac: boolean
var isLinux: boolean
var cmd: 'cmd' | 'ctrl'
var formatDate: typeof format
var formatDateToNow: typeof formatDistanceToNow
var debounce: Utils['debounce']
var sortBy: Utils['sortBy']
var isUndefined: Utils['isUndefined']
var isString: Utils['isString']
var createChoiceSearch: (
choices: Choice[],
config: Partial<Options & ConfigOptions>
) => Promise<(query: string) => ScoredChoice[]>
var setScoredChoices: (scoredChoices: ScoredChoice[]) => Promise<void>
var groupChoices: (
choices: Choice[],
options?: {
groupKey?: string
missingGroupName?: string
order?: string[]
sortChoicesKey?: (string | boolean)[]
recentKey?: string
recentLimit?: number
excludeGroups?: string[]
}
) => Choice[]
var formatChoices: (choices: Choice[], className?: string) => Choice[]
var preload: (scriptPath?: string) => void
var setSelectedChoices: (choices: Choice[]) => Promise<void>
var toggleAllSelectedChoices: () => Promise<void>
var trace: Trace
type Metadata = import('./core.js').Metadata
var ai: {
(
systemPrompt: string,
options?: {
model?: string | LanguageModelV1
temperature?: number
maxTokens?: number
}
): (input: string) => Promise<string>
object: <Schema extends ZodTypeAny>(
promptOrMessages: string | CoreMessage[],
schema: Schema,
options?: {
model?: string | LanguageModelV1
temperature?: number
maxTokens?: number
}
) => Promise<z.infer<Schema>>
}
var assistant: (
systemPrompt: string,
options?: {
model?: string | LanguageModelV1
temperature?: number
maxTokens?: number
tools?: Record<string, Tool<any, any>>
maxSteps?: number
autoExecuteTools?: boolean
maxHistory?: number
}
) => {
addUserMessage: (content: string | any[]) => void
addSystemMessage: (content: string) => void
addAssistantMessage: (
text?: string,
options?: { toolCalls?: ToolCallPart[]; parts?: CoreMessage['content'] }
) => void
addMessage: (message: CoreMessage) => void
textStream: AsyncGenerator<string, void, unknown>
stop: () => void
generate: (abortSignal?: AbortSignal) => Promise<AssistantOutcome>
messages: CoreMessage[]
lastInteraction?: AssistantLastInteraction | null
get autoExecuteTools(): boolean
set autoExecuteTools(value: boolean)
get maxHistory(): number
}
var generate: <Schema extends ZodTypeAny>(
promptOrMessages: string | CoreMessage[],
schema: Schema,
options?: {
model?: string | LanguageModelV1
temperature?: number
maxTokens?: number
}
) => Promise<z.infer<Schema>>
var metadata: Metadata
var z: typeof import('zod').z
}

// File: kitapp.d.ts
import { execaCommand as exec } from 'execa'
import type { editor as editorApi } from './editor.api'
import {
type Key as CoreKeyEnum,
Channel,
Mode,
type statuses,
type PROMPT as CORE_PROMPT,
} from '../core/enum.js'
import type { AppDb } from '../core/db.js'
import {
type Action,
type AppState,
ChannelHandler,
type Choice,
Choices,
type FlagsObject,
type PromptConfig,
type PromptData,
type ScoredChoice,
type Script,
type Shortcut,
} from './core.js'
import type { BrowserWindowConstructorOptions, Display, Rectangle } from './electron.js'
import type { Trash } from './packages.js'
import type { marked } from '../globals/marked.js'
import type { Token as MarkedToken } from 'marked'
import type { ChildProcess } from 'node:child_process'
import type { UiohookKeyboardEvent, UiohookMouseEvent, UiohookWheelEvent } from './io.js'
import type { KeyEnum } from '../core/keyboard.js'
import type { FileSearchOptions } from './platform.js'
import type { NotificationConstructorOptions } from './notify.js'
import type { ShebangConfig } from '../core/shebang.js'
import type { Readable } from 'node:stream'
interface ToastOptions {
pauseOnHover?: boolean
pauseOnFocusLoss?: boolean
closeOnClick?: boolean
autoClose?: number | false
hideProgressBar?: boolean
draggable?: boolean | 'mouse' | 'touch'
draggablePercent?: number
}
export type Toast = (toast: string, options?: ToastOptions) => void
export type Prompt = {
closeActions(): Promise<void>
close(): void
openActions(): void
setInput(input: string): void
focus(): Promise<void>
blur(): Promise<void>
hide(): Promise<void>
}
export type GetMediaDevices = () => Promise<MediaDeviceInfo[]>
export type GetTypedText = () => Promise<string>
placeholderOrConfig?: string | PromptConfig,
options?: FileSearchOptions
) => Promise<string>
config?: EditorConfig & { hint?: string },
actions?: Action[]
) => Promise<string>) & {
setSuggestions: (suggestions: string[]) => Promise<void>
setConfig: (config: EditorConfig) => Promise<void>
append: (text: string) => Promise<void>
getSelection: () => Promise<{
text: string
start: number
end: number
}>
getCursorOffset: () => Promise<number>
moveCursor: (offset: number) => Promise<void>
insertText: (text: string) => Promise<void>
setText: (text: string) => Promise<void>
}
export type PromptBounds = {
x: number
y: number
width: number
height: number
}
export type PromptDb = {
screens: {
[screenId: string]: {
[scriptId: string]: PromptBounds
}
}
}
export type Drop = (placeholder?: string | PromptConfig, actions?: Action[]) => Promise<any>
template: string,
config?: EditorConfig,
actions?: Action[]
) => Promise<string>
html?:
| string
| {
html?: string
hint?: string
},
formData?: any
) => Promise<any>
export type Form = (html: string | PromptConfig, formData?: any, actions?: Action[]) => Promise<any>
type Field =
| {
label?: string
placeholder?: string
value?: string
type?: string
required?: boolean
min?: number
max?: number
step?: number
pattern?: string
[key: string]: string | boolean | number
}
| string
export type Fields = (
fields: Field[] | (PromptConfig & { fields: Field[] }),
actions?: Action[]
) => Promise<string[]>
type EmojiObject = {
activeSkinTone: string
emoji: string
names: string[]
unified: string
unifiedWithoutSkinTone: string
}
export type Div = (html?: string | DivConfig, actions?: Action[]) => Promise<any>
type SetImage = string | { src: string }
type AddChoice = (choice: string | Choice) => Promise<void>
type SetChoices = (
choices: (Choice | string)[],
config?: {
className?: string
skipInitialSearch?: boolean
inputRegex?: string
generated?: boolean
}
) => Promise<void>
type SetFormData = (formData: any) => Promise<void>
type AppendChoices = (choices: Choice[]) => Promise<void>
type SetTextAreaOptions = {
value?: string
placeholder?: string
}
type DisabledThottlingConfig = Pick<
PromptConfig,
| 'headerClassName'
| 'footerClassName'
| 'ui'
| 'inputHeight'
| 'itemHeight'
| 'placeholder'
| 'scriptPath'
>
export type SetIgnoreBlur = (ignoreBlur: boolean) => void
export type SetPanel = (html: string, containerClasses?: string) => Promise<void>
export type SetPrompt = (config: Partial<PromptData>) => Promise<void>
export type SetPreview = (html: string, containerClasses?: string) => Promise<void>
{
content: string
timestamp: string
}[]
>
export type Submit = (value: any) => Promise<void>
type ScriptHandler = (scriptPath: string) => void
type ScriptEventHandler = (handler: ScriptHandler) => removeListener
markdownPath: string,
options?:
| Partial<PromptConfig>
| ((sections?: GuideSection[], tokens?: MarkedToken[]) => Promise<Partial<PromptConfig>>)
) => Promise<T>
declare global {
var textarea: TextArea
var drop: Drop
var div: Div
var form: Form
var fields: Fields
var emoji: Emoji
var editor: Editor
var template: Template
var hotkey: Hotkey
var send: Send
var sendWait: (channel: Channel, value?: any, timeout?: number) => Promise<any>
var headers: Record<string, string>
var sendResponse: (body: any, headers?: Record<string, string>) => Promise<any>
var sendWaitLong: (channel: Channel, value?: any, timeout?: number) => Promise<any>
var setFocused: SetFocused
var setEnter: SetEnter
var setPlaceholder: SetPlaceholder
var setPanel: SetPanel
var setFooter: SetFooter
var addChoice: AddChoice
var appendChoices: AppendChoices
var setChoices: SetChoices
var setFormData: SetFormData
var clearTabs: () => void
var setDiv: SetPanel
var setPreview: SetPreview
var setPrompt: SetPrompt
var setBounds: SetBounds
var getBounds: GetBounds
var getActiveScreen: GetActiveScreen
var setHint: SetHint
var setName: SetName
var setDescription: SetDescription
var setInput: SetInput
var appendInput: SetInput
var scrollTo: ScrollTo
var setFilterInput: SetInput
var setTextareaValue: SetTextareaValue
var setIgnoreBlur: SetIgnoreBlur
var setResize: SetResize
var setPauseResize: SetResize
var setLoading: SetLoading
var setProgress: SetProgress
var setRunning: SetLoading
var setStatus: SetStatus
var setTheme: SetTheme
var setScriptTheme: SetTheme
var showImage: ShowAppWindow
var show: () => Promise<void>
var hide: (hideOptions?: HideOptions) => Promise<void>
var blur: () => Promise<void>
var dev: (object?: any) => Promise<void>
var getClipboardHistory: () => Promise<ClipboardItem[]>
var clearClipboardHistory: () => Promise<void>
var getEditorHistory: GetEditorHistory
var removeClipboardItem: (id: string) => Promise<void>
var setTab: (tabName: string) => void
var submit: Submit
var mainScript: (input?: string, tab?: string) => Promise<void>
var appKeystroke: SendKeystroke
var Key: typeof CoreKeyEnum
var log: typeof console.log
var warn: typeof console.warn
var keyboard: Keyboard
var mouse: Mouse
var clipboard: KitClipboard
var execLog: ExecLog
var focus: () => Promise<void>
var setAlwaysOnTop: (alwaysOnTop: boolean) => Promise<void>
var docs: Docs
var getAppState: any
var registerShortcut: RegisterShortcut
var unregisterShortcut: UnregisterShortcut
var startDrag: (filePath: string, iconPath?: string) => void
var eyeDropper: () => Promise<{
sRGBHex: string
}>
var chat: Chat
var toast: Toast
var find: Find
var mic: Mic
var screenshot: Screenshot
var webcam: WebCam
var prompt: Prompt
var getMediaDevices: GetMediaDevices
var getTypedText: GetTypedText
var PROMPT: typeof PROMPT_OBJECT
var preventSubmit: symbol
type removeListener = () => void
var onClick: (callback: (event: UiohookMouseEvent) => void) => removeListener
var onMousedown: (callback: (event: UiohookMouseEvent) => void) => removeListener
var onMouseup: (callback: (event: UiohookMouseEvent) => void) => removeListener
var onWheel: (callback: (event: UiohookWheelEvent) => void) => removeListener
var onKeydown: (callback: (event: UiohookKeyboardEvent) => void) => removeListener
var onKeyup: (callback: (event: UiohookKeyboardEvent) => void) => removeListener
var system: System
var app: App
var getTheme: () => Promise<KitTheme>
var notify: Notify
}

// File: notify.ts


// File: packages.d.ts
import type * as shelljs from 'shelljs/index'
import type { add, clone, commit, init, pull, push, addRemote } from 'isomorphic-git'
export type Trash = (
input: string | readonly string[],
option?: {
glob?: boolean
}
) => Promise<void>
export type Git = {
clone: (
repo: string,
dir: string,
options?: Partial<Parameters<typeof clone>[0]>
) => ReturnType<typeof clone>
pull: (dir: string, options?: Partial<Parameters<typeof pull>[0]>) => ReturnType<typeof pull>
push: (dir: string, options?: Partial<Parameters<typeof push>[0]>) => ReturnType<typeof push>
add: (
dir: string,
glob: string,
options?: Partial<Parameters<typeof add>[0]>
) => ReturnType<typeof add>
  ...
}
export type OpenApp = typeof import('open').openApp
type Degit = (repo: string, options?: DegitOptions) => IDegit
declare global {
var cd: typeof shelljs.cd
var cp: typeof shelljs.cp
var chmod: typeof shelljs.chmod
var echo: typeof shelljs.echo
var exit: typeof shelljs.exit
var grep: typeof shelljs.grep
var ln: typeof shelljs.ln
var ls: typeof shelljs.ls
var mkdir: typeof shelljs.mkdir
var mv: typeof shelljs.mv
var pwd: typeof shelljs.pwd
var sed: typeof shelljs.sed
var tempdir: typeof shelljs.tempdir
var test: typeof shelljs.test
var which: typeof shelljs.which
var paste: () => Promise<string>
var copy: (text: string) => Promise<void>
var trash: Trash
var open: Open
var openApp: OpenApp
var rm: Trash
var git: Git
var degit: Degit
var tmpPromise: TmpPromise
var memoryMap: Map<string, any>
var onTabIndex: number
}

// File: platform.d.ts
import type { ProcessInfo } from './core.js'
import type { Display, Point } from './electron.js'
import type { BrowserContextOptions, Page, PageScreenshotOptions } from 'playwright'
type PlayAudioFile = (path: string, options?: any) => Promise<string>
type StopAudioFile = () => Promise<void>
type CopyPathAsImage = (path: string) => Promise<string>
interface FileSearchOptions {
onlyin?: string
kind?: string
kMDItemContentType?: string
}
type FileSearch = (name: string, fileSearchOptions?: FileSearchOptions) => Promise<string[]>
type Browser = 'Google Chrome' | 'Brave' | 'Firefox' | 'Edge'
type GetActiveTab = (browser?: Browser) => Promise<string>
type GetTabs = (browser?: Browser) => Promise<{ url: string; title: string }[]>
type FocusTab = (url: string, browser?: Browser) => Promise<string>
interface ScrapeOptions {
headless?: boolean
timeout?: number
browserOptions?: BrowserContextOptions
}
type ScrapeSelector<T = any> = (
url: string,
selector: string,
transform?: (element: any) => T,
options?: ScrapeOptions
) => Promise<T[]>
type ScrapeAttribute = (
url: string,
selector: string,
attribute: string,
options?: ScrapeOptions
) => Promise<string | null>
interface ScreenshotFromWebpageOptions {
timeout?: number
browserOptions?: BrowserContextOptions
screenshotOptions?: PageScreenshotOptions
}
type GetScreenshotFromWebpage = (
url: string,
options?: ScreenshotFromWebpageOptions
) => Promise<Buffer>
interface WebpageAsPdfOptions {
timeout?: number
browserOptions?: BrowserContextOptions
pdfOptions?: Parameters<Page['pdf']>[0]
mediaOptions?: Parameters<Page['emulateMedia']>[0]
}
type GetWebpageAsPdf = (url: string, options?: WebpageAsPdfOptions) => Promise<Buffer>
interface Window {
process: string
title: string
index: number
}
type GetWindows = () => Promise<Window[]>
type FocusWindow = (process: string, title: string) => Promise<string>
interface WindowBounds {
process: string
name: string
position: { x: number; y: number }
size: { width: number; height: number }
fullscreen: boolean
}
type GetWindowsBounds = () => Promise<WindowBounds[]>
type GetWindowPosition = (process: string, title: string, x: number, y: number) => Promise<string>
type SetWindowPosition = (process: string, title: string, x: number, y: number) => Promise<string>
type SetWindowSizeByIndex = (
process: string,
index: number,
x: number,
y: number
) => Promise<string>
type SetWindowBoundsByIndex = (
process: string,
index: number,
x: number,
y: number,
width: number,
height: number
) => Promise<string>
type ScatterWindows = () => Promise<string>
type OrganizeWindows = () => Promise<void>
type SetWindowPositionByIndex = (
process: string,
index: number,
x: number,
y: number
) => Promise<string>
type SetWindowSize = (process: string, title: string, x: number, y: number) => Promise<string>
interface Screen {
name: string
x: number
y: number
width: number
height: number
}
type GetScreens = () => Promise<Display[]>
type SelectDisplay = (includeThumbnails?: boolean) => Promise<Display>
type TileWindow = (app: string, leftOrRight: 'left' | 'right') => Promise<string>
type GetActiveScreen = () => Promise<Display>
type GetMousePosition = () => Promise<Point>
type GetProcesses = () => Promise<ProcessInfo[]>
interface Rectangle {
x: number
y: number
width: number
height: number
}
export interface Prompt {
id: string
pid: number
birthTime: number
isFocused: boolean
isVisible: boolean
isDestroyed: boolean
bounds: Rectangle
focus: () => Promise<void>
exit: () => Promise<void>
hide: () => Promise<void>
scriptPath: string
name: string
}
type GetPrompts = () => Promise<Prompt[]>
type AttemptScriptFocus = () => Promise<boolean>
type GetPromptStatus = () => Promise<{
status: Array<{
windowId: number
pid: number
boundToProcess: boolean
scriptPath: string
isVisible: boolean
isFocused: boolean
isDestroyed: boolean
isIdle: boolean
}>
summary: {
total: number
visible: number
bound: number
orphaned: number
idle: number
}
}>
type CleanupPrompts = () => Promise<{
cleaned: number
status: Array<{
windowId: number
pid: number
boundToProcess: boolean
scriptPath: string
isVisible: boolean
isFocused: boolean
isDestroyed: boolean
isIdle: boolean
}>
summary: {
total: number
visible: number
bound: number
orphaned: number
idle: number
}
}>
type ForcePromptCleanup = () => Promise<{
cleaned: number
status: Array<{
windowId: number
pid: number
boundToProcess: boolean
scriptPath: string
isVisible: boolean
isFocused: boolean
isDestroyed: boolean
isIdle: boolean
}>
summary: {
total: number
visible: number
bound: number
orphaned: number
idle: number
}
}>
interface KitWindow {
name: string
id: string
value: string
bounds: Rectangle
isFocused: boolean
isVisible: boolean
isDestroyed: boolean
}
type GetKitWindows = () => Promise<KitWindow[]>
type FocusAppWindow = (id: string) => Promise<void>
interface Bounds {
left: number
top: number
right: number
bottom: number
}
type SetActiveAppBounds = (bounds: Bounds) => Promise<void>
type SetActiveAppPosition = (position: { x: number; y: number }) => Promise<void>
type SetActiveAppSize = (size: { width: number; height: number }) => Promise<void>
type GetActiveAppInfo = () => Promise<{
localizedName: string
bundleIdentifier: string
bundleURLPath: string
executableURLPath: string
isFinishedLaunching: boolean
processIdentifier: number
windowTitle: string
windowIndex: number
windowID: number
x: number
y: number
width: number
height: number
}>
type GetActiveAppBounds = () => Promise<Bounds>
type GetSelectedFile = () => Promise<string>
type SetSelectedFile = (filePath: string) => Promise<void>
type GetSelectedDir = () => Promise<string>
type SelectFile = (message?: string) => Promise<string>
type RevealFile = (filePath: string) => Promise<string>
type RevealInFinder = (filePath?: string) => Promise<void>
type SelectFolder = (message?: string) => Promise<string>
type GetSelectedText = () => Promise<string>
type CutText = () => Promise<string>
type Lock = () => Promise<unknown>
type Logout = () => Promise<unknown>
type Sleep = () => Promise<unknown>
type Shutdown = () => Promise<unknown>
type QuitAllApps = (appsToExclude?: string) => Promise<unknown>
type Say = (text: string, options?: any) => Promise<string>
type Beep = () => Promise<void>
type SetSelectedText = (text: string, hide?: boolean) => Promise<void>
type KeyStroke = (keyString: string) => Promise<string>
type AppleScript = (script: string, options?: any) => Promise<string>
declare global {
var applescript: AppleScript
var beep: Beep
var copyPathAsImage: CopyPathAsImage
var fileSearch: FileSearch
var focusTab: FocusTab
var focusWindow: FocusWindow
var getActiveAppInfo: GetActiveAppInfo
var getActiveAppBounds: GetActiveAppBounds
var getActiveScreen: GetActiveScreen
var getActiveTab: GetActiveTab
var getMousePosition: GetMousePosition
var getProcesses: GetProcesses
var getPrompts: GetPrompts
var attemptScriptFocus: AttemptScriptFocus
var getKitWindows: GetKitWindows
var focusKitWindow: FocusAppWindow
var getScreens: GetScreens
var selectDisplay: SelectDisplay
var getSelectedFile: GetSelectedFile
var revealInFinder: RevealInFinder
var selectFile: SelectFile
var selectFolder: SelectFolder
var revealFile: RevealFile
var getSelectedText: GetSelectedText
var cutText: CutText
var getTabs: GetTabs
var getWindows: GetWindows
var getWindowsBounds: GetWindowsBounds
var getSelectedDir: GetSelectedDir
var keystroke: KeyStroke
var logout: Logout
var lock: Lock
var openLog: () => void
var organizeWindows: OrganizeWindows
var playAudioFile: PlayAudioFile
var stopAudioFile: StopAudioFile
var quitAllApps: QuitAllApps
var say: Say
var scatterWindows: ScatterWindows
var scrapeAttribute: ScrapeAttribute
var scrapeSelector: ScrapeSelector
var getScreenshotFromWebpage: GetScreenshotFromWebpage
var getWebpageAsPdf: GetWebpageAsPdf
var setActiveAppBounds: SetActiveAppBounds
var setActiveAppPosition: SetActiveAppPosition
var setActiveAppSize: SetActiveAppSize
var setSelectedText: SetSelectedText
var setSelectedFile: SetSelectedFile
var setWindowBoundsByIndex: SetWindowBoundsByIndex
var setWindowPosition: SetWindowPosition
var setWindowPositionByIndex: SetWindowPositionByIndex
var setWindowSize: SetWindowSize
var setWindowSizeByIndex: SetWindowSizeByIndex
var shutdown: Shutdown
var sleep: Sleep
var tileWindow: TileWindow
var getPromptStatus: GetPromptStatus
var cleanupPrompts: CleanupPrompts
var forcePromptCleanup: ForcePromptCleanup
}

// File: pro.d.ts
import type { ForkOptions } from 'node:child_process'
import type { Channel } from '../core/enum.js'
import type { Action, PromptConfig } from './core.js'
import type { BrowserWindowConstructorOptions, Display, Rectangle } from './electron.js'
type ViteWidgetSendMessage = {
channel: string
pid: number
targetId: string
widgetId: number
[key: string]: any
}
declare global {
var widget: Widget
var vite: ViteWidget
var menu: Menubar
var term: Terminal
var showLogWindow: ShowLogWindow
}
